# GitHub Labels Configuration
# Can be synced using github-label-sync or similar tools

# Types
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: question
  color: d876e3
  description: Further information is requested

# Priority
- name: "priority: critical"
  color: b60205
  description: Critical priority issue

- name: "priority: high"
  color: d93f0b
  description: High priority issue

- name: "priority: medium"
  color: fbca04
  description: Medium priority issue

- name: "priority: low"
  color: 0e8a16
  description: Low priority issue

# Status
- name: triage
  color: fef2c0
  description: Needs to be triaged

- name: "in progress"
  color: 2E7D32
  description: Work in progress

- name: blocked
  color: e11d48
  description: Blocked by another issue or external factor

- name: stale
  color: ffffff
  description: No recent activity

# Components
- name: core
  color: 1d76db
  description: Related to blz-core

- name: cli
  color: 1d76db
  description: Related to blz-cli

- name: mcp
  color: 1d76db
  description: Related to blz-mcp

- name: rust
  color: dea584
  description: Rust code changes

# Workflow
- name: "good first issue"
  color: 7057ff
  description: Good for newcomers

- name: "help wanted"
  color: 008672
  description: Extra attention is needed

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency

- name: ci
  color: 000000
  description: Related to CI/CD

- name: tests
  color: bfd4f2
  description: Related to testing

# Special
- name: security
  color: ee0701
  description: Security issue or improvement

- name: performance
  color: d4c5f9
  description: Performance related issue or improvement

- name: breaking-change
  color: ee0701
  description: Breaking change that requires major version bump