name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feat', 'feature']
  - title: '🐛 Fixes'
    labels: ['fix', 'bugfix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor', 'perf']
  - title: '📝 Documentation'
    labels: ['docs']
  - title: '⚙️ CI/CD'
    labels: ['ci']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No user-facing changes.'
template: |
  ## Changes
  $CHANGES
