reviews:
  # Stop posting "Review skipped" status comments on non-default branches
  review_status: false

  auto_review:
    enabled: true
    # Base branches to review (accepts regex patterns)
    base_branches:
      - "main"         # Default branch
      - "gt/.*"        # Matches Graphite branches like gt/feature-name
      - "gt-.*/.*"     # Matches Graphite stacks like gt-v0.3/branch-name
