id = "langchain-js"
name = "LangChain JavaScript (Index)"
description = "LangChain JavaScript documentation index - links to full docs"
url = "https://js.langchain.com/llms.txt"
category = "framework"
tags = ["ai", "llm", "javascript", "typescript", "agents", "index"]
registeredAt = "2025-09-30T20:00:00Z"
verifiedAt = "2025-09-30T20:00:00Z"

[aliases]
github = ["langchain-ai/langchainjs"]
npm = ["langchain", "@langchain/core"]
