id = "vercel"
name = "Vercel"
description = "Vercel platform documentation - deployment, serverless, edge functions"
url = "https://vercel.com/llms.txt"
category = "platform"
tags = ["hosting", "deployment", "serverless", "edge", "platform"]
registeredAt = "2025-09-30T20:00:00Z"
verifiedAt = "2025-09-30T20:00:00Z"

[aliases]
npm = ["vercel"]
github = ["vercel/vercel"]