# Cargo configuration for blz
# Host/OS specific tweaks stay here; shared profile defaults live in `Cargo.toml`.

[build]
# Number of parallel jobs, defaults to # of CPUs
jobs = 8

[target.'cfg(target_os = "macos")']
# Optimize for the local CPU architecture when building on macOS hosts.
# GitHub Actions runners report inconsistent CPU capabilities under Linux
# virtualization, and `target-cpu=native` can produce binaries that cause
# SIGILL when build scripts run during CI. Limit this tweak to macOS where
# we actually benefit from it for local development.
rustflags = ["-C", "target-cpu=native"]

# Shared profile defaults now live in the workspace `Cargo.toml`.
# Keep this file focused on host-specific tweaks and developer conveniences.

[alias]
# Convenient aliases
lint = "clippy -- -D warnings"
lint-all = "clippy --all-targets --all-features -- -D warnings"
fix = "clippy --fix --allow-dirty --allow-staged"
test-all = "test --all-features"
bench-all = "bench --all-features"
