name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    # Allow specific bots (@copilot[bot], @devin[bot], @coderabbitai[bot]) and all humans to trigger Claude
    if: |
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '@claude') &&
       (github.event.comment.user.type != 'Bot' ||
        contains(fromJSON('["copilot[bot]", "devin[bot]", "coderabbitai[bot]"]'), github.event.comment.user.login))) ||
      (github.event_name == 'pull_request_review_comment' &&
       contains(github.event.comment.body, '@claude') &&
       (github.event.comment.user.type != 'Bot' ||
        contains(fromJSON('["copilot[bot]", "devin[bot]", "coderabbitai[bot]"]'), github.event.comment.user.login))) ||
      (github.event_name == 'pull_request_review' &&
       contains(github.event.review.body, '@claude') &&
       (github.event.review.user.type != 'Bot' ||
        contains(fromJSON('["copilot[bot]", "devin[bot]", "coderabbitai[bot]"]'), github.event.review.user.login)))
    runs-on: ubuntu-latest
    concurrency:
      group: claude-${{ github.event.pull_request.number || github.event.issue.number || github.run_id }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Allow Claude to run Rust/Cargo commands for this repository
          allowed_tools: "Bash(cargo build*),Bash(cargo test*),Bash(cargo clippy*),Bash(cargo fmt*),Bash(cargo deny*),Bash(cargo shear*),Bash(make *),Bash(just *)"
          
          # Custom instructions for the blz Rust project
          custom_instructions: |
            This is a Rust project using Tantivy for search indexing.
            Follow the rules in .agent/rules/DEVELOPMENT.md
            Use cargo for all build/test operations
            Ensure all code passes clippy with no warnings
            Write tests for any new functionality
            Update AGENTS.md if making architectural changes
          
          # Environment variables for Rust development
          claude_env: |
            RUST_BACKTRACE: 1

# This workflow responds to explicit @claude mentions in pull requests only
# Allowed triggers:
# - PR comments with @claude (not regular issues)
# - PR review comments with @claude
# - PR review submissions with @claude
#
# Allowed comment sources:
# - All human users
# - Specific bots: @copilot[bot], @devin[bot], @coderabbitai[bot]
# All other bots are ignored to prevent unwanted automation loops
