name: Dependency Security & Management (manual)

on:
  # Run explicitly when we want a deeper dependency audit. Keeping this
  # workflow manual avoids adding noise to every PR.
  workflow_dispatch:
    inputs:
      include-dependency-review:
        description: 'Run GitHub dependency review action'
        required: false
        default: 'true'

jobs:
  dependency-review:
    name: Dependency Review
    if: inputs.include-dependency-review == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          warn-only: true
          deny-licenses: GPL-3.0, AGPL-3.0, SSPL-1.0
          vulnerability-check: true
          license-check: true
