name: Dependency Security & Management (manual)

on:
  # Run explicitly when we want a deeper dependency audit. Keeping this
  # workflow manual avoids adding noise to every PR.
  workflow_dispatch:
    inputs:
      include-dependency-review:
        description: 'Run GitHub dependency review action'
        type: boolean
        required: false
        default: true
      base-ref:
        description: 'Base ref to compare against (defaults to main)'
        required: false
        default: 'main'
      head-ref:
        description: 'Head ref/commit for comparison (defaults to the checked-out commit SHA)'
        required: false
        default: ''

jobs:
  dependency-review:
    name: Dependency Review
    if: inputs.include-dependency-review
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Resolve refs for dependency review
        id: refs
        run: |
          base="${{ inputs.base-ref }}"
          if [ -z "$base" ]; then
            base="main"
          fi

          head="${{ inputs.head-ref }}"
          if [ -z "$head" ]; then
            head="${{ github.sha }}"
          fi

          echo "base=$base" >> "$GITHUB_OUTPUT"
          echo "head=$head" >> "$GITHUB_OUTPUT"

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          warn-only: true
          deny-licenses: GPL-3.0, AGPL-3.0, SSPL-1.0
          vulnerability-check: true
          license-check: true
          base-ref: ${{ steps.refs.outputs.base }}
          head-ref: ${{ steps.refs.outputs.head }}
