name: Homebrew Tap Bump

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump:
    name: Bump Homebrew formula in outfitter-dev/homebrew-tap
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          # Name of the formula in the tap
          formula-name: blz
          # Target tap repository (must exist and be writeable by the token)
          tap: outfitter-dev/homebrew-tap
          # Use the tag name from the release (e.g., v0.1.0)
          tag: ${{ github.ref_name }}
          # PAT with repo access on the tap repository
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
