name: Homebrew Tap Bump
permissions:
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump:
    name: Bump Homebrew formula in outfitter-dev/homebrew-tap
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: blz
          tap: outfitter-dev/homebrew-tap
          tag: ${{ github.ref_name }}
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
