name: Miri (Unsafe Validation)

on:
  pull_request:
    paths:
      - 'crates/blz-core/**'
      - '.github/workflows/miri.yml'
  schedule:
    - cron: '0 2 * * MON'  # Runs at 02:00 UTC every Monday
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: miri-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  MIRIFLAGS: -Zmiri-disable-isolation -Zmiri-ignore-leaks

jobs:
  miri:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: miri-nightly
          cache-on-failure: false
      
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri, rust-src
      
      - name: Setup Miri
        run: cargo +nightly miri setup
      
      - name: Run miri tests (blz-core lib only)
        run: |
          if [ ! -f crates/blz-core/Cargo.toml ]; then
            echo "::warning::blz-core not found, skipping Miri tests"
            exit 0
          fi
          cargo +nightly miri test -p blz-core --lib -- -q
        continue-on-error: true
      
      - name: Report Miri results
        if: always()
        run: |
          echo "::notice::Miri validation completed. Check logs for any undefined behavior warnings."
