name: release-drafter
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "closed"

permissions:
  contents: write

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
